### ISSUE TITLE
[BUG] Galleryview: Title/Images sometimes not immediatley shown until viewport update

### ISSUE THREAD

**Issue by DerLeole** [tech-kev/SharedMoments#2]
Problem:
In the galleryview, completely randomly, sometimes the data that is supposed to be fecthed via the inline jQuery script, isn't displayed on pageload, but only after wards, when the viewport is forced to reload, with for example resizing the browser window.

![image](https://github.com/tech-kev/SharedMoments/assets/12782603/8afce5b5-bdaf-4911-bb82-afa3ebd0f3cb)

However in rare, but also random cases, the title isn't updated from the locales in time, and then it reads "undefined: whatever".
This can not be fixed by resizing the window.

![image](https://github.com/tech-kev/SharedMoments/assets/12782603/dbea4ab7-fbdf-4084-8f5f-60cc85c178fe)
![image](https://github.com/tech-kev/SharedMoments/assets/12782603/39567d9d-62d2-4bf0-9e42-88e16a8321ef)

No errors are thrown or Network requests blocked.

**Comment by tech-kev** [comment]
Thanks for reporting the issue!
I will release an update that should fix the two bugs. If this is not the case, please let me know.
