### ISSUE TITLE
[Feature Request] - Add .mov videos and .m4a audio-files and login/logout function

### ISSUE THREAD

**Issue by cruunnerr** [tech-kev/SharedMoments#4]
First of all...Thank you! Really great work. I like it pretty much.

However I just noticed that adding new videos or Voice messages via iPhone is not possible, since iPhones uses .m4a for audio files and .mov with HECV Codec for videos.

Second thing would be a logout function and/or the possibility for a second factor like a yubikey for the login. 

Since I am still trying out, I will find more ideas. 
But again....great work. I really appreciate when people do not upload all there private things to any 3rd Party Cloud. 
You have given us the opportunity to archive and record all our upcoming memories. A digital family book, in other words.

**Comment by tech-kev** [comment]
Thank you for your kind words. I'm really glad that you like it.

I will provide an update that addresses the points you mentioned.
I will integrate voice messages in a future release, as that requires a bit more customization.
The same applies to login via YubiKey.

I'm always open to new ideas and welcome any suggestions.

**Comment by tech-kev** [comment]
Solved with commit https://github.com/tech-kev/SharedMoments/commit/bb6b075f36c67293c8a6682e80bf3fa679c97233.
